%%{init: { 'theme': 'base', 'themeVariables': { 'cScale0': '#e3f2fd', 'cScale1': '#ffcdd2', 'cScale2': '#e3f2fd', 'cScale3': '#ffcdd2', 'cScale4': '#e8f5e9' } } }%%
timeline
    title Historia y evolución del aprendizaje automático

    section Raíces y Era Simbólica
        1805 a 1960s : 1805 Mínimos Cuadrados : 1936 Análisis Discriminante Lineal : 1943 Neuronas biológicas : 1950 Test de Turing : 1956 Seminario de Dartmouth : 1960s Expectativas desmedidas

    section Primer Invierno
        1970s : Fracaso del modelo Perceptrón simple : Caída de expectativas y recorte de fondos

    section Resurgimiento Simbólico
        1980s : Auge de los Sistemas Expertos : Nuevas esperanzas en la IA

    section Segundo Invierno
        1987 a 1993 : Mantenimiento costoso de sistemas : Dificultad para escalar : Nuevo recorte de fondos

    section ML y Deep Learning
        1990s a 2020s : 1990s Florecimiento del ML (datos/hardware) : 2012 Revolución Deep Learning (ImageNet) : 2017 Arquitectura Transformer (PLN) : 2020s IA Generativa a gran escala (LLMs)
