%%{init: { 'theme': 'base', 'themeVariables': { 'cScale0': '#e3f2fd', 'cScale1': '#ffcdd2', 'cScale2': '#e3f2fd', 'cScale3': '#ffcdd2', 'cScale4': '#e8f5e9' } } }%%
timeline
    title History and evolution of machine learning

    section Roots and the Symbolic Era
        1805 to 1960s : 1805 Least Squares : 1936 Linear Discriminant Analysis : 1943 Biological neuron model : 1950 Turing Test : 1956 Dartmouth Workshop : 1960s Excessive expectations

    section First Winter
        1970s : Failure of the simple Perceptron model : Collapse of expectations and funding cuts

    section Symbolic Resurgence
        1980s : Rise of Expert Systems : Renewed hopes for AI

    section Second Winter
        1987 to 1993 : Costly system maintenance : Difficulty scaling : Renewed funding cuts

    section ML and Deep Learning
        1990s to 2020s : 1990s ML flourishes (data/hardware) : 2012 Deep Learning revolution (ImageNet) : 2017 Transformer architecture (NLP) : 2020s Large-scale Generative AI (LLMs)
